COMP: Add missing ObjectFactory header
To address:

  /ITKUltrasound/include/itkFrequencyDomain1DFilterFunction.h: In static
  member function 'static itk::FrequencyDomain1DFilterFunction::Pointer
  itk::FrequencyDomain1DFilterFunction::New()':
  /ITK/Modules/Core/Common/include/itkMacro.h:292:24: error: 'ObjectFactory'
  is not a member of 'itk'
       Pointer smartPtr = ::itk::ObjectFactory< x >::Create();