COMP: use std::unordered_map instead of itksys::hash_map
[21/52] Generating C:/P/IPP/ITK-win_37-x64/Wrapping/itkSpectra1DImageFilter.xml
FAILED: C:/P/IPP/ITK-win_37-x64/Wrapping/itkSpectra1DImageFilter.xml
cmd.exe /C "cd /D D:\a\im\_skbuild\win-amd64-3.7\cmake-build\Wrapping\Modules\Ultrasound && D:\a\im\_skbuild\win-amd64-3.7\cmake-build\Wrapping\Generators\CastXML\castxml\bin\castxml.exe -o C:/P/IPP/ITK-win_37-x64/Wrapping/itkSpectra1DImageFilter.xml --castxml-gccxml --castxml-start _wrapping_ --castxml-cc-msvc ( "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe" /DWIN32 /D_WINDOWS /W3 /GR /EHsc /bigobj /bigobj ) -fexceptions -w -c @C:/P/IPP/ITK-win_37-x64/Wrapping/Ultrasound.castxml.inc C:/P/IPP/ITK-win_37-x64/Wrapping/itkSpectra1DImageFilter.cxx"
In file included from C:/P/IPP/ITK-win_37-x64/Wrapping/itkSpectra1DImageFilter.cxx:17:
D:/a/im/include\itkSpectra1DImageFilter.h:30:10: fatal error: 'itksys/hash_map.hxx' file not found
#include "itksys/hash_map.hxx"
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.