COMP: ITKv5 no longer supports legacy method signatures for VNL
This commit fixes error like the following reported when building
SlicerITKUltrasound extension:

  /path/to/SlicerITKUltrasound-Release/ITKUltrasound/include/itkLinearLeastSquaresGradientImageFilter.hxx:97:43: error: ‘vnl_math_sgn0’ was not declared in this scope; did you mean ‘vnl_math_h_’?
     97 |   int          previousSgn = vnl_math_sgn0(nit.GetPixel(s.start()));
        |                              ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
        |                              vnl_math_h_


Sources have been updated running "VNL_ModernizeNaming.py" script:

cd ITKUltrasound
for f in $(fd -e cxx -e hxx); do
  python3 /path/to/ITK/Utilities/Maintenance/VNL_ModernizeNaming.py $f;
done