COMP: Add missing include CornerOffsets
Addresses:

/home/matt/src/ITKUltrasound/include/itkBoxSigmaSqrtNMinusOneImageFilter.h:73:41:
error: use of undeclared identifier 'CornerOffsets'
  std::vector<OffsetType> UnitCorners =
  CornerOffsets<TInputImage>(accImage);
                                          ^